[package]
name = "emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.3", features = ["derive"] }
log = { version = "0.4.20", features = ["std"] }
macros = { path = "../macros" }
sdl2 = "0.35.2"
