name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install llvm tools reuired for coverage
      run: rustup component add llvm-tools-preview
    - name: Build
      run: |
        export RUSTFLAGS="-Cinstrument-coverage"
        cargo build --verbose
    - name: Run tests
      run: |
        export LLVM_PROFILE_FILE="emulator-%p-%m.profraw"
        cargo test --verbose
    - name: Generate coverage
      run: |
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
        ./grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
        cat lcov.info
        bash <(curl -s https://codecov.io/bash) -f lcov.info
#    - uses: codecov/codecov-action@v3
#      with:
#        files: ./lcov.info
