name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependency
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: Update Rust
      run: rustup update
    - name: Install llvm tools and grcov required for coverage
      run: |
        rustup component add llvm-tools-preview
        cargo install grcov
    - name: Build and Run tests with coverage
      run: |
        cargo build --verbose
        cargo test --verbose --lib
      env:
        RUSTFLAGS: -Cinstrument-coverage
        LLVM_PROFILE_FILE: emulator-%p-%m.profraw
    - name: Generate coverage
      run: |
        grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info
    - uses: codecov/codecov-action@v3
      with:
        files: ./lcov.info
